### ISSUE TITLE
Investigate external libraries for full-text indices on MariaDB

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#126]
SQL Alchemy does not natively support creation of fullt-text indices.
Investigate https://github.com/mengzhuo/sqlalchemy-fulltext-search

**Comment by MaxFrax** [comment]
Currently our projects database setup is the following:
```
dialect: mysql
driver: pymysql
storage engine:*'INNODB
MariaDB version: 10.0.36
```

From https://mariadb.com/kb/en/library/full-text-index-overview/:

> Full-text indexes can be used only with MyISAM and Aria tables, from MariaDB 10.0.5 with InnoDB tables and from MariaDB 10.0.15 with Mroonga tables, and can be created only for CHAR, VARCHAR, or TEXT columns.

As we can see from above **our current configuration** INNODB against MariaDB 10.0.36 **does not support full text indices**.

*NOTICE: The we are using this MariaDB version due to current Mix-n-match tool forge setup.*

**Comment by MaxFrax** [comment]
There is another useful take away from the MariaDB docs: index in our scenario should be created after the huge data insertion. In this way we will achieve better performances.

**Comment by MaxFrax** [comment]
It seems that the docs are wrong. I've just tried to create a full text index and the `show index from` query shows it. Actually, using also the `MATCH AGAINST` construct returns results.

**Comment by marfox** [comment]
> It seems that the docs are wrong. I've just tried to create a full text index and the `show index from` query shows it. Actually, using also the `MATCH AGAINST` construct returns results.

Indeed, I have already tried to build full-text indices in #35
