### ISSUE TITLE
On URL validation after dump import

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#134]
Discogs use case: It took **8 days**, 4 hours, and 27 minutes to validate 662,975 + 197,389 = **860,364 URLs**, discarding 109,250.

**Comment by MaxFrax** [comment]
This issue is related to #179

**Comment by MaxFrax** [comment]
**PROPOSAL**

Resolving URIs is the most time-consuming activity in the importation phase. So our goal changes from a simple time reduction to avoiding unnecessary URI resolutions.

As currently is, URI resolution only happens if the URI is built correctly. This means that our new system will kick in just after our usual `invalid()` check returns `valid`.

The first time the system runs, it performs a normal full import, like we already do.
Since the second time, it will assume the links inside the database are valid, and link by link performs an incremental change to our database table. Basically, from the second time, only the diff of links is resolved!
Adopting this approach raises the problem on how to ensure the links in the database are valid. We can assume they are valid if it has been a little time since the last import, but when is the optimal time to resolve them again?
It's not trivial to chose the right heuristic, so I propose to have two separate commands to trigger the two behaviours and let the user decide.

This whole approach does not fix the long times of the first import, but I wanted to share my first thoughts. 
I'm already working to design something better.

**Comment by MaxFrax** [comment]
We chose a simple approach: the importer can run resolving URLs or not depending on the user choice.
`python -m soweego importer import` comes with a new option which is `--resolve/--no-resolve` to keep/skip the `.resolve()` calls.

To resolve the URLs at a later stage, `python -m soweego importer validate_links` shall be used.
