### ISSUE TITLE
Mappings from IMDb professions to Wikidata

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#165]
Find mappings from the list of professions in IMDb to Wikidata classes.
@tupini07 , can you please paste here the full list of professions with your mappings?

## Approach
1. Check actual usage: https://github.com/Wikidata/soweego/issues/165#issuecomment-460563724
2. Look at schema/ontology consistency: https://github.com/Wikidata/soweego/issues/165#issuecomment-460568387

## Frequency of occupations in IMDb
![photo5934044898145709696](https://user-images.githubusercontent.com/4838312/52267682-fd3cb680-2939-11e9-917f-3465d5619e59.jpg)

**Comment by tupini07** [comment]
These are the mappings I've found up until now:

**Concepts for which there exists a direct mapping in Wikidata:**

> actor => Q33999
> actress => Q33999 (same ^)
> art_director => Q706364
> assistant_director => Q1757008
> casting_director => Q1049296
> cinematographer => Q222344
> composer => Q36834
> costume_designer => Q1323191
> director => Q3455803
> executive => Q978044
> manager => Q2462658
> producer => Q13235160
> production_designer => Q2962070
> production_manager => Q21292974
> publicist => Q4178004
> set_decorator => Q6409989
> special_effects => Q21560152
> stunts => Q465501
> talent_agent => Q1344174
> writer => Q28389

**Concepts of which have ambiguous mapping:**

> editor => Q7042855 film editor, Q23016178 tv editor

**Concepts with a possible mapping but is not an exact match:**

> animation_department => possibly Q266569 animator
> assistant => possibly Q23835475 Helper
> camera_department => possibly Q1208175 Camera operator
> legal => possibly Q40348 Lawyer
> visual_effects => maybe one of these: Q1364080 VFX producer, Q1224742 digital image technician, Q28122965 effects animator

**Concepts for which I haven't found any mapping:**

> art_department 
> casting_department
> costume_department
> editorial_department
> electrical_department
> location_management
> make_up_department
> miscellaneous
> music_department
> production_department
> script_department
> sound_department
> soundtrack
> transportation_department

**Comment by tupini07** [comment]
[This IMDB page](https://help.imdb.com/article/contribution/filmography-credits/adding-filmography-credits/GAB5B33MBLEG73CT?ref_=__seemr#) defines how to properly attribute _roles_ (which are also called _credits_, and which we here call _professions_) to people, and it also defines the possible roles. We can use these definitions to find the more appropriate mappings to Wikidata.

**Comment by MaxFrax** [comment]
@tupini07 What about this https://www.wikidata.org/wiki/Q4797184 as `art_department` mapping?

**Comment by MaxFrax** [comment]
@marfox @tupini07 What about using the "music works" class as mapping for `music_department`?
https://www.wikidata.org/wiki/Q22965078
https://help.imdb.com/article/contribution/filmography-credits/music-department/G9QPJV4FV85BRM7X?ref_=helpms_helpart_inline#

**Comment by MaxFrax** [comment]
@tupini07 I would map `soundtrack` to https://www.wikidata.org/wiki/Q217199

**Comment by tupini07** [comment]
Thanks @MaxFrax ! I'm thinking that the concepts you mentioned are not _occupations_, I don't know if this would be a problem since the IMDB data tells us which are the main occupations of a person.

For the `soundtrack` mapping, I think we can cluster it, together with the other "music" occupations, under `musician` (see #164)

**Comment by marfox** [comment]
> @tupini07 What about this https://www.wikidata.org/wiki/Q4797184 as `art_department` mapping?
This item doesn't seem to be actually used as a **class** in Wikidata.

The general rule of thumb to find a relevant mapping is to **query Wikidata for its usage**, trying the following queries at https://query.wikidata.org:
```
# P31 = instance of
SELECT DISTINCT ?item WHERE { ?item wdt:P31/wdt:P279* wd:CLASS_QID_HERE } LIMIT 10
```
or
```
# P106 = occupation
SELECT DISTINCT ?item WHERE { ?item wdt:P106/wdt:P279* wd:CLASS_QID_HERE } LIMIT 10
```
`Q4797184` returns almost no results.

**Comment by marfox** [comment]
> @marfox @tupini07 What about using the "music works" class as mapping for `music_department`?
> https://www.wikidata.org/wiki/Q22965078
> https://help.imdb.com/article/contribution/filmography-credits/music-department/G9QPJV4FV85BRM7X?ref_=helpms_helpart_inline#

The IMDb link you pointed out suggests that `music_department` boils down to musicians. OK, _"not covered by `composer` or `soundtrack`"_, but still musicians.
So I would cluster this under `musician`: `Q639669`, see #164

**Comment by tupini07** [comment]
I checked the jobs of 300 random people from the imdb dump with `animation_department` as one of their main professions. The graph below shows the most common jobs.

![figure_1](https://user-images.githubusercontent.com/3422347/52795376-f1579f80-3071-11e9-9543-d957c92e8177.png)

Below are the occurences of the top 7 jobs in Wikidata, as well as their respective QID.

```
animator (Q266569) : 3217
animation director (Q779815) : 130
Key animator (Q2850035) : 0
background artist (Q4839644) : 164
inbetweener (Q3153626) : 6
assistant animator (Q28798045) : 7
character designer (Q1062952) : 128
```

Based on this I think we could map the `animation_department` occupation to `animator (Q266569)`. What do you think?

**Comment by marfox** [comment]
@tupini07 , I really appreciate your devotion for data analysis!

> Based on this I think we could map the `animation_department` occupation to `animator (Q266569)`. What do you think?

Fully agree.
Feel free to close this task **with the final mapping as closing comment**.

**Comment by tupini07** [comment]
To save space, I've checked the remaining IMDB professions and I think we should use the following mappings:

```
```

The reasons for each of these professions can be seen by expanding the appropriator section below:

<details><summary>visual_effects</summary>
<p>

#### yes, even hidden code blocks!

```python
print("hello world!")
```

</p>
</details>

**Comment by tupini07** [comment]
To save space, I've checked the remaining IMDB professions and I think we should use the following mappings:

```
visual_effects: visual effects artist (Q1224742)
art_department: artist (Q483501)
casting_department: casting director (Q1049296)
costume_department: costume maker (Q59341113)
editorial_department: assistant editor (Q29168399)
electrical_department: electrician (Q165029)
location_management: location manager (Q1093536)
make_up_department: make-up artist (Q935666)
production_department: production assistant (Q2867219)
script_department: script supervisor (Q1263187)
transportation_department: driver (Q352388)
```

*Note: for the `editorial_department` mapping, we might want to consider changing it to be the same as `editor`, since the `assistant editor` occupation has no occurrences in wikidata.*

The reasons for why I chose each of these professions can be seen by expanding the appropriator section below. The analysis for each profession was made by taking 300 random people with said profession as part of their `primaryProfessions` in the IMDB dump. Then the top 7 jobs related from that profession were obtained whenever possible.


<details><summary>visual_effects</summary>
<p>

![visual_effects_popular_jobs](https://user-images.githubusercontent.com/3422347/53015322-1ae64180-344b-11e9-8c86-e316bb1f933b.png)


Top 7 jobs:

```
visual effects artist (Q1224742) : 8803
visual effects supervisor (Q8311) : 88

other jobs had almost no occurrences
```
</p>
</details>

<details><summary>art_department</summary>
<p>

![art_department_popular_jobs](https://user-images.githubusercontent.com/3422347/53015330-1faaf580-344b-11e9-887d-98c02e3170f0.png)

Top 7 jobs:

```
set dresser (Q3054941) : 1
property master (Q1430377) : 14
storyboard artist (Q5762300) : 199
graphic designer (Q627325) : 8753
graphic artist (Q1925963) : 19377
art director (Q706364) : 2979
props : No match
```

These are all a bit diverse, so I've decided to cluster them under `artist (Q483501)`.

</p>
</details>

<details><summary>casting_department</summary>
<p>

![casting_department_popular_jobs](https://user-images.githubusercontent.com/3422347/53015355-26396d00-344b-11e9-886a-a06ca63756ea.png)


Top 7 jobs:

```
casting director (Q1049296) : 151
wardrobe (Q7969198) : 0
```

The rest of the top *casting jobs* had no clear mapping on Wikidata. 

</p>
</details>

<details><summary>costume_department</summary>
<p>

![costume_department_popular_jobs](https://user-images.githubusercontent.com/3422347/53015364-32252f00-344b-11e9-89ed-cda882519dc2.png)


Top 7 jobs:

```
costumer maker (Q59341113) : 6
wardrobe supervisor (Q7969198) : 0
```

The rest of the top *costume dreparment* jobs had no clear mapping on Wikidata. 

</p>
</details>

<details><summary>editorial_department</summary>
<p>

![editorial_department_popular_jobs](https://user-images.githubusercontent.com/3422347/53015374-37827980-344b-11e9-8fef-a4cd585c93e4.png)


Top 7 jobs:

```
assistant editor (Q29168399) : 0
film colorist (Q61743042) : 1
additional editor (Q28020090) : 0
```

I was a bit unsure if we should map this department to only `film editor (Q7042855) : 4299`, but seeing that in the sample data there are a bit more than 1000 `assistant editor`s and only a bit less than 100 editors, I chose to stick with `assistant editor`, since it *represents* best the sample. Although we might consider it changing it since it has no occurences in Wikidata.

</p>
</details>

<details><summary>electrical_department</summary>
<p>

![electrical_department_popular_jobs](https://user-images.githubusercontent.com/3422347/53015380-3bae9700-344b-11e9-8655-c2c74928ce1f.png)


Top 7 jobs:

```
electrician (Q165029) : 144
```

</p>
</details>

<details><summary>location_management</summary>
<p>

![location_management_popular_jobs](https://user-images.githubusercontent.com/3422347/53015384-423d0e80-344b-11e9-8c56-31f8a1ce882d.png)


Top 7 jobs:

```
location manager (Q1093536) : 14
```

</p>
</details>

<details><summary>make_up_department</summary>
<p>

![make_up_department_popular_jobs](https://user-images.githubusercontent.com/3422347/53015389-4701c280-344b-11e9-8a93-a64784364c6f.png)


Top 7 jobs:

```
make-up artist (Q935666) : 492
hairdresser (Q55187) : 313
```
</p>
</details>

<details><summary>production_department</summary>
<p>

![production_department_popular_jobs](https://user-images.githubusercontent.com/3422347/53015398-4d903a00-344b-11e9-939e-4cc92e0500c3.png)


Top 7 jobs:

```
production assistant (Q2867219) : 16

Other 2 jobs had no matches in Wikidata. 
```
</p>
</details>

<details><summary>script_department</summary>
<p>

![script_department_popular_jobs](https://user-images.githubusercontent.com/3422347/53015404-53861b00-344b-11e9-9d3f-9610b13cdf98.png)


Top 7 jobs:

```
script supervisor (Q1263187) : 37
```
</p>
</details>

<details><summary>transportation_department</summary>
<p>

![transportation_department_popular_jobs](https://user-images.githubusercontent.com/3422347/53015410-57b23880-344b-11e9-8ecd-3d0ef9d92539.png)


Top 7 jobs:

```
driver (Q352388) : 3696
```
</p>
</details>

**Comment by marfox** [comment]
@marfox , great job.

One comment: when there are **zero** occurrences in Wikidata, there is no point in having a mapping.

This applies for instance to `editorial_department` (which represents a mere **1.3%** of the IMDb dump, by the way).

**Comment by tupini07** [comment]
Perfect! In that case I think the mapping processes is complete. These are the final mappings:

```
actor : Q33999
actress : Q33999
animation_department : Q266569
art_department : Q483501
art_director : Q706364
assistant_director : Q1757008
camera_department : Q1208175
casting_department : Q1049296
casting_director : Q1049296
cinematographer : Q222344
composer : Q36834
costume_department : Q59341113
costume_designer : Q1323191
director : Q2526255
editor : Q7042855
electrical_department : Q165029
executive : Q978044
location_management : Q1093536
make_up_department : Q935666
manager : Q2462658
music_department : Q639669
producer : Q3282637
production_department : Q2867219
production_designer : Q2962070
production_manager : Q21292974
publicist : Q4178004
script_department : Q1263187
set_decorator : Q6409989
sound_department : Q128124
soundtrack : Q639669
special_effects : Q21560152
stunts : Q465501
talent_agent : Q1344174
transportation_department : Q352388
visual_effects : Q1224742
writer : Q28389
```

_Just as a note, the correctness of this list can be verified by piping it through this command:
`while read line; do echo $line; wd s $(echo $line | cut -d" " -f3-); echo "------"; done;`
It uses [wikidata-cli](https://github.com/maxlath/wikidata-cli) to get the relevant information for each QID._
