### ISSUE TITLE
Build a stopwords list for bands

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#263]
Based on the assessment of the uploaded statements as per #260, we found that many errors in the classification of bands are due to specific stopwords that confuse the classifiers.

Starting points are:
1. instances of band, e.g., _band, orchestra, choir_, etc.;
2. musical genres, e.g., _jazz, blues_, etc.

**Comment by MaxFrax** [comment]
Add the stopwords in `text_utils`

**Comment by MaxFrax** [comment]
In the following table the 50 most frequent tokens.
`total_rows = 418836`

Token | Frequency | frequency/total_rows %
-- | -- | --
band | 8128 | 1,94%
orchestra | 7664 | 1,83%
trio | 3630 | 0,87%
choir | 2798 | 0,67%
quartet | 2623 | 0,63%
ensemble | 2520 | 0,60%
los | 2296 | 0,55%
black | 2117 | 0,51%
les | 1860 | 0,44%
boys | 1824 | 0,44%
new | 1814 | 0,43%
brothers | 1673 | 0,40%
die | 1640 | 0,39%
big | 1540 | 0,37%
project | 1517 | 0,36%
jazz | 1501 | 0,36%
blue | 1268 | 0,30%
dead | 1136 | 0,27%
red | 1116 | 0,27%
stars | 1098 | 0,26%
symphony | 1095 | 0,26%
club | 1072 | 0,26%
sound | 1059 | 0,25%
group | 1057 | 0,25%
soul | 1052 | 0,25%
music | 1024 | 0,24%
blues | 1014 | 0,24%
quintet | 1006 | 0,24%
singers | 954 | 0,23%
city | 931 | 0,22%
one | 927 | 0,22%
love | 896 | 0,21%
radio | 896 | 0,21%
orchestre | 868 | 0,21%
del | 861 | 0,21%
chamber | 847 | 0,20%
john | 827 | 0,20%
chorus | 822 | 0,20%
king | 802 | 0,19%
death | 735 | 0,18%
string | 722 | 0,17%
men | 720 | 0,17%
family | 709 | 0,17%
four | 708 | 0,17%
duo | 693 | 0,17%
white | 657 | 0,16%
five | 653 | 0,16%
little | 644 | 0,15%
orchester | 636 | 0,15%
der | 631 | 0,15%

**Comment by MaxFrax** [comment]
In the following table the 50 most frequent tokens in `discogs_group`.
`total_rows = 7297399`


Token | Frequency | frequency/total_rows %
-- | -- | --
orchestra | 59061 | 0,008093432
john | 46539 | 0,006377478
band | 45012 | 0,006168225
david | 36534 | 0,005006441
michael | 30821 | 0,00422356
paul | 30377 | 0,004162716
peter | 27269 | 0,003736811
van | 26745 | 0,003665004
mike | 25127 | 0,003443282
james | 24035 | 0,003293639
chris | 22296 | 0,003055335
robert | 22153 | 0,003035739
martin | 21371 | 0,002928578
jean | 21344 | 0,002924878
mark | 20478 | 0,002806205
thomas | 20440 | 0,002800998
steve | 19715 | 0,002701648
dave | 19177 | 0,002627923
joe | 18889 | 0,002588457
trio | 17803 | 0,002439636
smith | 17142 | 0,002349056
richard | 16876 | 0,002312605
tom | 16586 | 0,002272865
daniel | 16480 | 0,002258339
ensemble | 16463 | 0,002256009
choir | 16017 | 0,002194892
bob | 15610 | 0,002139118
lee | 15400 | 0,002110341
jose | 15225 | 0,00208636
los | 15067 | 0,002064708
george | 14967 | 0,002051005
tony | 14772 | 0,002024283
frank | 14711 | 0,002015924
chorus | 14394 | 0,001972484
big | 13610 | 0,001865048
bill | 13514 | 0,001851893
jones | 13415 | 0,001838326
jim | 13153 | 0,001802423
scott | 13152 | 0,001802286
brown | 13150 | 0,001802012
alex | 13139 | 0,001800505
black | 12862 | 0,001762546
eric | 12735 | 0,001745142
maria | 12375 | 0,00169581
jan | 12157 | 0,001665936
williams | 12078 | 0,00165511
charles | 12002 | 0,001644696
jack | 11749 | 0,001610026
dan | 11747 | 0,001609752
quartet | 11700 | 0,001603311

Steps to obtain the table:
```
# To get the total rows
select count(*) from soweego.`discogs_group`;
# To get the table without the percentages (% done with excel :) )
SET GLOBAL innodb_ft_aux_table = 'soweego/discogs_group';

select word, sum(doc_count) as occ from (select distinct word, first_doc_id, last_doc_id, doc_count from information_schema.INNODB_FT_INDEX_TABLE) as u group by word order by occ desc limit 50;

# To check the tokens counts. I've taken 3 random tokens and checked the values matched with the table
select count(*) from soweego.discogs_group where match(name_tokens) against ('+jean' in boolean mode);
```

**Comment by MaxFrax** [comment]
> 1. instances of band, e.g., band, orchestra, choir, etc.;

Are we really sure to remove those words @marfox ?
As you can see in the following example, there would be many mistakes due to that choice.

Probably instead of removing those tokens from the database, we should change how the similar match works. The first idea that comes to my mind is to remove those tokens only when performing a similar match. 

`select catalog_id, name, name_tokens from soweego.musicbrainz_band where match(name_tokens) against ('+ray +charles' in boolean mode) order by catalog_id;`


catalog_id | name | name_tokens
-- | -- | --
1e86edd8-0ca8-4f7c-b01f-6a619ccbf1c2 | Ray Charles and His Orchestra | charles orchestra ray
41c48805-e2f9-4d8f-9d1b-8be17e5e724b | Ray Charles Trio | trio charles ray
45454652-8a12-4e58-a003-0e1956ac1f75 | Il Coro Di Ray Charles | il ray coro di charles
45454652-8a12-4e58-a003-0e1956ac1f75 | Ray Charles & Chorus | charles ray chorus
45454652-8a12-4e58-a003-0e1956ac1f75 | The Ray Charles Choir | choir charles ray
45454652-8a12-4e58-a003-0e1956ac1f75 | The Ray Charles Chorus | charles ray chorus
a534d84e-f764-403e-bbd4-8968e852738a | Ray Charles Singers | charles singers ray
a534d84e-f764-403e-bbd4-8968e852738a | The Ray Charles Singers | charles singers ray
b675404e-1afb-4bf0-a243-49563468d689 | The Ray Charles Big Band | band big charles ray
c3b096d6-054b-4946-91db-31b0cf63f852 | Ray & Charles | charles ray


`select catalog_id, name, name_tokens from soweego.discogs_group where match(name_tokens) against ('+ray +charles' in boolean mode) order by catalog_id;`

catalog_id | name | name_tokens
-- | -- | --
1227913 | The Ray Charles Orchestra | orchestra ray charles
1227913 | The Ray Charles Big Band | band big ray charles
1396742 | Charles & Ray | ray charles
1396742 | Charles And Ray | ray charles
1405714 | Il Coro Di Ray Charles | ray il coro di charles
1405714 | Ray Charles & Chorus | chorus ray charles
1405714 | Ray Charles Chorus | chorus ray charles
1405714 | The Ray Charles Choir | choir ray charles
1405714 | The Ray Charles Chorus | chorus ray charles
1435254 | Ray Charles (3) | ray charles
1559315 | Ray Charles With The Raelets | raelets ray charles
1917146 | Ray Charles Quartet | quartet ray charles
1929454 | Charles Ray | ray charles
2208769 | Ray Charles McCullough | mccullough ray charles
2208769 | Ray Charles McCullough II | mccullough ii ray charles
2321883 | X-Ray Charles (2) | ray charles
2426351 | Ray Charles Vs. Dio | dio vs ray charles
2487604 | Ray Charles (4) | ray charles
2542418 | Charles Ray (2) | ray charles
2750499 | Ray Charles RPM Studio; Los Angeles | los rpm ray studio angeles charles
2751386 | The Ray Charles Trio | trio ray charles
2751386 | Ray Charles Trio | trio ray charles
3160111 | Charles Ray & The Righteous Kind | kind righteous ray charles
3187353 | Lou Rawls & Ray Charles | lou rawls ray charles
3217976 | Charles Ray Hancock | hancock ray charles
3250605 | Ray Charles & His Band | band ray charles
3250605 | Ray Charles Band | band ray charles
3250605 | The Ray Charles Band | band ray charles
3250605 | Ray Charles And His Band | band ray charles
3315813 | X-Ray Charles (3) | ray charles
353827 | \The Ray Charles Singers\"" | singers ray charles
353827 | I Ray Charles Singers | singers ray charles
353827 | Los Cantantes De Ray Charles | los ray de cantantes charles
353827 | Ray Charles Choir | choir ray charles
353827 | Ray Charles Quintet | quintet ray charles
353827 | Ray Charles Singers | singers ray charles
353827 | Ray Charles Vocal Group | vocal group ray charles
353827 | The Ray Charles Choir | choir ray charles
353827 | The Ray Charles Singers | singers ray charles
353827 | The Ray Charles Vocal Group | vocal group ray charles
353827 | The Ray Charles Singers | singers ray charles
3862085 | Ray Charles (5) | ray charles
3956551 | The Ray Charles Quintet | quintet ray charles
4184422 | Ray Charles (6) | ray charles
4227083 | Ray Charles White | white ray charles
4289788 | The Ray Charles Choir | choir ray charles
4311886 | Ray Charles McCulloch II | ii mcculloch ray charles
4361666 | Ray Charles And Orchestra | orchestra ray charles
4706960 | The Ray Charles Quartet | quartet ray charles
4718223 | Ray Charles With String Orchestra & Chorus | chorus ray string orchestra charles
4718223 | Ray Charles With String Orchestra And Chorus | chorus ray string orchestra charles
4851697 | Ray Charles Brown | brown ray charles
4851697 | Ray Charles Brown Jr | jr brown ray charles
4851697 | Ray Charles Brown Jr. | jr brown ray charles
4900582 | Ray Charles (7) | ray charles
5003903 | Neal Hefti And His Orchestra With The Ray Charles Choir | choir ray hefti neal orchestra charles
521963 | Ray Charles | ray charles
521963 | Ray Charles & His Orch. | orch ray charles
521963 | Ray Charles & His Orchestra | orchestra ray charles
521963 | Ray Charles And His Orch. | orch ray charles
521963 | Ray Charles And His Orchestra And Chorus | chorus orchestra ray charles
521963 | Ray Charles And Orchestra | orchestra ray charles
521963 | Ray Charles Con Orchestra | con orchestra ray charles
521963 | Ray Charles E La Sua Orchestra | ray sua la orchestra charles
521963 | Ray Charles Et Son Grand Orchestre | orchestre ray grand son et charles
521963 | Ray Charles Et Son Orchestre | orchestre ray son et charles
521963 | Ray Charles His Orchestra And Chorus | chorus orchestra ray charles
521963 | Ray Charles His Trio And Orchestra | trio orchestra ray charles
521963 | Ray Charles Orchestra | orchestra ray charles
521963 | Ray Charles With Chorus And Orch. | orch chorus ray charles
521963 | Ray Charles With Chorus And Orchestra | chorus orchestra ray charles
521963 | Ray Charles With His Orchestra | orchestra ray charles
521963 | Ray Charles With Orchestra | orchestra ray charles
521963 | Ray Charles With Orchestra And Chorus | chorus orchestra ray charles
521963 | Ray Charles; His Orchestra And Chorus | chorus orchestra ray charles
521963 | The Ray Charles Chorus And Orchestra | chorus orchestra ray charles
521963 | The Ray Charles Orchestra | orchestra ray charles
521963 | The Ray Charles Orchestra And Chorus | chorus orchestra ray charles
521963 | Ray Charles And His Orchestra | orchestra ray charles
5308218 | Ray Charles Band | band ray charles
5428954 | The Ray Charles Foundation | foundation ray charles
5428955 | The Ray Charles Marketing Group | group marketing ray charles
5486172 | Ray Charles / B.B. King | king ray charles
5535311 | Charles Ray Martin | martin ray charles
5881892 | Ray Charles Ives | ives ray charles
5955267 | Ray Charles Jr. | jr ray charles
6165174 | Ray Charles (8) | ray charles
6168256 | Dr. X-Ray Charles | dr ray charles
6252039 | Dorothy Evans; Arthur Malvin And Ray Charles | arthur evans ray dorothy malvin charles
6350005 | Charles Ray Hastings Jr. | hastings jr ray charles
6386374 | Ray Charles Robinson Jr | robinson jr ray charles
6454844 | Charles Ray (3) | ray charles
6670027 | Ray Charles Levette | levette ray charles
6734027 | Lara Fabian Et Ray Charles | ray lara fabian et charles
6744625 | X-Ray Charles (4) | ray charles
6760475 | El Club de Ray Charles | ray el club de charles
6771205 | Ray Charles And Orchestra (2) | orchestra ray charles
679527 | Donald Ray Charles | donald ray charles
6959900 | Little Ray Charles | charles ray little
7066593 | The Raelets* / Ray Charles Orchestra* | raelets orchestra ray charles

**Comment by marfox** [comment]
> > 1. instances of band, e.g., band, orchestra, choir, etc.;
> 
> Are we really sure to remove those words @marfox ?
> As you can see in the following example, there would be many mistakes due to that choice.
> 
> Probably instead of removing those tokens from the database, we should change how the similar match works. The first idea that comes to my mind is to remove those tokens only when performing a similar match.

While the effect is likely to be the same,  I think it still makes sense to give a **very low** weight to those tokens.

**Comment by MaxFrax** [comment]
## Single layer perceptron before and after the implementation

### MusicBrainz


  |   | Before | After | Variation
-- | -- | -- | -- | --
Precision | mean | 0,952637439 | 0,952590289323280000 | -0,00004714991567
  | std deviation | 0,001407241 | 0,002896673507020860 | 0,00148943234000
Recall | mean | 0,869642505 | 0,870808055676028000 | 0,00116555053546
  | std deviation | 0,002295089 | 0,003696932895618800 | 0,00140184432062
F-score | mean | 0,909246736 | 0,909853560814431000 | 0,00060682506258
  | std deviation | 0,000955081 | 0,000954665432649848 | -0,00000041512026
Predictions over 0,5 |   | 1171 | 1299 | 128



![Figure_1](https://user-images.githubusercontent.com/3145452/56728488-2c9ddb00-6753-11e9-8f63-0a5f2048e657.png)

As you can see in the table, there are no significant precision/recall changes.
The Venn diagram shows how much the before and the after result sets overlap each other. As you can see, the result set changes are significant.

### Discogs


  |   | Before | After | Variation
-- | -- | -- | -- | --
Precision | mean | 0,783097605 | 0,782646494896037000 | -0,00045111025726
  | std deviation | 0,004130891 | 0,004707345844041910 | 0,00057645495430
Recall | mean | 0,94570117 | 0,945713332109572000 | 0,00001216215665
  | std deviation | 0,001934997 | 0,003097076749311750 | 0,00116207977187
F-score | mean | 0,856748701 | 0,856475171290665000 | -0,00027352928251
  | std deviation | 0,003048751 | 0,002757466367834650 | -0,00029128483827
Predictions over 0,5 |   | 17018 | 17037 | 19



![Figure_1](https://user-images.githubusercontent.com/3145452/56728808-f6ad2680-6753-11e9-81b2-9bc5577901b8.png)

On Discogs basically nothing happens. 


### Further investigation

It would be a good idea to check also the prediction score distribution before and after.
Checking also the other linkers would be useful, too.
